### ISSUE TITLE
Does `inquirer` needs to be a `dependency`?

### ISSUE THREAD

**Issue by mfranzke** [db-ui/gif#13]
It's unclear how the [defined `dependency`](https://github.com/db-ui/gif/blob/main/package.json#L29) [`inquirer`](https://www.npmjs.com/package/inquirer) is being used and whether it could be a `devDependency` instead of need to be included at all (maybe it's a leftover).

**Comment by nmerget** [comment]
Yes, it was a leftover. I removed it
