### ISSUE TITLE
What about multicolored svgs – should we support it?

### ISSUE THREAD

**Issue by annsch** [db-ui/gif#15]
Currently all colors are transformed to one color. Maybe this is done by svg-cleanup?

**Comment by mfranzke** [comment]
> Currently all colors are transformed to one color. Maybe this is done by svg-cleanup?

If I'm not mistaken, fonts could still only include a single `color` definition; so the `functional` icons are meant to be single colored, whereas the `illustrative` aren't being transformed to icon fonts, as they are multi-colored.

**Comment by nmerget** [comment]
As @mfranzke said, this won't be possible

**Comment by mfranzke** [comment]
> As @mfranzke said, this won't be possible

to my knowledge it's only possible of you overlay the icon parts by having one of them within `::before` and the other in `::after` `content`-properties. But that's a little bit more complicated and we don't have the need at the moment.
